# Generated by Django 4.1.2 on 2022-10-15 06:56

import apps.short_urls.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.CharField(default=apps.short_urls.services.UuidService.short_uuid,
                 max_length=10, primary_key=True, serialize=False, unique=True)),
                ('long_url', models.CharField(max_length=256)),
                ('visits', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-visits'],
            },
        ),
    ]
